services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - DATABASE_URL=mysql://propartuser:cwG3e3n5K9KknrmKMlhj@127.0.0.1:3306/proparthub
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: host
