services:
  app:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=your_secret_key_here_change_this_in_production
      - FLASK_DEBUG=False
      - HUBSPOT_API_KEY=${HUBSPOT_API_KEY:-}